github: [cristiangirlea]
buymeacoffee: "https://www.buymeacoffee.com/cristiangirlea"
paypal: "https://www.paypal.me/cristiangirleaDev"
custom:
  - "mailto:cristiangirlea@gmail.com"
  - "https://www.linkedin.com/in/cristian-girlea/"
